global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "scale_alerts.yml"


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.1.100:9100']

  - job_name: 'VM'
    static_configs:
      - targets: ['192.168.1.45:9100']
